### ISSUE TITLE
Reader macro not defined

### ISSUE THREAD

**Issue by ghost** [arnoo/angelspie#1]
### Platform

* Manjaro 23.0
* Hy 0.26.0
* pipen v2023.7.11
* Angelspie 0.9.1

### Issue

A fatal error occurs when calling the command `pipenv run hy angelspie.hy`

```
Traceback (most recent call last):
  File "<frozen runpy>", line 290, in run_path
  File "/home/<XXXXXXX>/angelspie09/angelspie.hy", line 47
    (defmacro _with-window [window #*forms]
                                         ^
hy.reader.exceptions.LexException: reader macro '#*forms' is not defined
```

As I don't know Hy, I don't have any more clue about what's going on… But I'll be glad to run some tests if it helps.

**Comment by arnoo** [comment]
Hello !

You say you are running hy 0.26.0 but I think that for some reason this is actually not the case: a syntax change has been introduced in hy 0.27.0 that would result in exactly the error you have. Maybe you have looked at `hy -v` instead of `pipenv run hy -v` ?

I've added commit https://github.com/arnoo/angelspie/commit/7f8976c5e4874c7e99d97c98aa1d017c42f91d76 to lock dependency versions as they should have been from the start. There's still work to be done to package the whole thing properly. The binary from the releases section is mostly useless, and with the dependency on system X libraries I have not yet had the time to find a suitable solution. I'll mention that in the readme.

**Comment by ghost** [comment]
> Maybe you have looked at hy -v instead of pipenv run hy -v ?

You are correct!

Thanks for looking into it.
